######################################################################
# Automatically generated by qmake (2.01a) Thu May 26 21:33:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
