######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 16 21:12:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
